apiVersion: v1
kind: Namespace
metadata:
  name: hacker-company

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: hacker-company
spec:
  selector:
    matchLabels:
      role: frontend
  replicas: 1
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hacker-company
spec:
  type: ClusterIP
  selector:
    role: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
